name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools twine
          python -m pip install -e ".[dev]"

      - name: Build package
        run: |
          bash build.sh

      - name: Verify tag matches version
        run: |
          # Extract version from the tag (remove 'v' prefix)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          # Extract version from pyproject.toml
          PACKAGE_VERSION=$(grep 'version = ' pyproject.toml | cut -d '"' -f2)
          # Check if versions match
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
